// BOOKING ACTION TYPES

export const CREATE_BOOKING = "CREATE_BOOKING";
export const CREATE_BOOKING_BEGIN = "CREATE_BOOKIGN_BEGIN";
export const CREATE_BOOKING_FAILED = "CREATE_BOOKING_FAILED";

export const LIST_BOOKINGS = "LIST_BOOKINGS";
export const START_LIST_BOOKINGS = "START_LIST_BOOKINGS";
export const FINISH_LIST_BOOKINGS = "FINISH_LIST_BOOKINGS";
export const LIST_BOOKINGS_FAIL = "LIST_BOOKINGS_FAIL";

export const EDIT_BOOKING_BEGIN = "EDIT_BOOKING_BEGIN";
export const EDIT_BOOKING = "EDIT_BOOKING";
export const EDIT_BOOKING_FAILED = "EDIT_BOOKING_FAILED";

export const DELETE_BOOKING_BEGIN = "DELETE_BOOKING_BEGIN";
export const DELETE_BOOKING = "DELETE_BOOKIGN";
export const DELETE_BOOKING_FAILED = "DELETE_BOOKING_FAILED";

// ROOM ACTION TYPES

export const FETCH_ROOMS = "FETCH_ROOMS";
export const FINISH_FETCHING_ROOMS = "FINISH_FETCHING_ROOMS";
export const BEGIN_FETCHING_ROOMS = "BEGIN_FETCHING_ROOMS";

export const ADD_ROOM_START = "ADD_ROOM_START";
export const ADD_ROOM_DONE = "ADD_ROOM_DONE";
export const ADD_ROOM_FAILED = "ADD_ROOM_FAILED";

export const EDIT_ROOM_START = "EDIT_ROOM_START";
export const EDIT_ROOM_DONE = "EDIT_ROOM_DONE";
export const EDIT_ROOM_FAILED = "EDIT_ROOM_FAILED";

export const DELETE_ROOM_BEGIN = "DELETE_ROOM_BEGIN";
export const DELETE_ROOM = "DELETE_ROOM";
export const DELETE_ROOM_FAILED = "DELETE_ROOM_FAILED";

//ROOM CATEGORIES

export const FETCH_ROOM_CATEGORIES_BEGIN = "FETCH_ROOM_CATEGORIES_BEGIN";
export const FETCH_ROOM_CATEGORIES = "FETCH_ROOM_CATEGORIES";
export const FETCH_ROOM_CATEGORIES_FAILED = "FETCH_ROOM_CATEGORIES_FAILED";

export const EDIT_ROOM_CATEGORY_BEGIN = "EDIT_ROOM_CATEGORY_BEGIN";
export const EDIT_ROOM_CATEGORY = "EDIT_ROOM_CATEGORY";
export const EDIT_ROOM_CATEGORY_FAILED = "EDIT_ROOM_CATEGORY_FAILED";

export const ADD_ROOM_CATEGORY_BEGIN = "ADD_ROOM_CATEGORY_BEGIN";
export const ADD_ROOM_CATEGORY = "ADD_ROOM_CATEGORY";
export const ADD_ROOM_CATEGORY_FAILED = "ADD_ROOM_CATEGORY_FAILED";

export const DELETE_ROOM_CATEGORY = "DELETE_ROOM_CATEGORY";
export const DELETE_ROOM_CATEGORY_BEGIN = "DELETE_ROOM_CATEGORY_BEGIN";
export const DELETE_ROOM_CATEGORY_FAILED = "DELETE_ROOM_CATEGORY_FAILED";

// USER ACTION TYPES

export const START_LOGIN = "START_LOGIN";
export const FINISH_LOGIN = "FINISH_LOGIN";
export const LOGIN_FAIL = "LOGIN_ERROR";

export const START_AUTO_LOGIN = "START_AUTO_LOGIN";
export const FINISH_AUTO_LOGIN = "FINISH_AUTO_LOGIN";
export const AUTO_LOGIN_FAILED = "AUTO_LOGIN_FAILED";

//STAFF ACTION TYPES

export const START_STAFF_FETCHING = "START_STAFF_FETCHING";
export const FINISH_STAFF_FETCHING = "FINISH_STAFF_FETCHING";
export const STAFF_FETCHING_FAILED = "STAFF_FETCHIGN_FAILED";

export const ADD_STAFF_MEMBER_BEGIN = "ADD_STAFF_MEMBER_BEGIN";
export const ADD_STAFF_MEMBER = "ADD_STAFF_MEMBER";
export const ADD_STAFF_MEMBER_FAILED = "ADD_STAFF_MEMBER_FAILED";

export const EDIT_STAFF_MEMBER_BEGIN = "EDIT_STAFF_MEMBER_BEGIN";
export const EDIT_STAFF_MEMBER = "EDIT_STAFF_MEMBER";
export const EDIT_STAFF_MEMBER_FAILED = "EDIT_STAFF_MEMBER_FAILED";

export const DEACTIVATE_STAFF_BEGIN = "DEACTIVATE_STAFF_BEGIN";
export const DEACTIVATE_STAFF = "DEACTIVATE_STAFF";
export const DEACTIVATE_STAFF_FAILED = "DEACTIVATE_STAFF_FAILED";


// HOTEL CLIENT ACTION TYPES

export const FETCH_HOTEL_CLIENTS_BEGIN = 'FETCH_HOTEL_CLIENTS_BEGIN'
export const FETCH_HOTEL_CLIENTS = 'FETCH_HOTEL_CLIENTS'
export const FETCH_HOTEL_CLIENTS_FAILED = 'FETCH_HOTEL_CLIENTS_FAILED'

export const UPDATE_HOTEL_CLIENT_BEGIN = 'UPDATE_HOTEL_CLIENT_BEGIN'
export const UPDATE_HOTEL_CLIENT = 'UPDATE_HOTEL_CLIENT'
export const UPDATE_HOTEL_CLIENT_FAILED = 'UPDATE_HOTEL_CLIENT_FAILED'

export const DELETE_HOTEL_CLIENT_BEGIN = 'DELETE_HOTEL_CLIENT_BEGIN'
export const DELETE_HOTEL_CLIENT = 'DELETE_HOTEL_CLIENT'
export const DELETE_HOTEL_CLIENT_FAILED = 'DELE_HOTEL_CLIENT_FAILED'


// HOTEL CLIENT EXPENSES


export const FETCH_CLIENT_EXPENSES_BEGIN = 'FETCH_CLIENT_EXPENSES_BEGIN'
export const FETCH_CLIENT_EXPENSES = 'FETCH_CLIENT_EXPENSES'
export const FETCH_CLIENT_EXPENSES_FAILED = 'FETCH_CLIENT_EXPENSES_FAILED'

export const ADD_CLIENT_EXPENSE = 'ADD_CLIENT_EXPENSE'
export const ADD_CLIENT_EXPENSE_BEGIN = 'ADD_CLIENT_EXPENSE_BEGIN'
export const ADD_CLIENT_EXPENSE_FAILED = 'ADD_CLIENT_EXPENSE_FAILED'

export const UPDATE_CLIENT_EXPENSE_BEGIN = 'UPDATE_CLIENT_EXPENSE_BEGIN'
export const UPDATE_CLIENT_EXPENSE = 'UPDATE_CLIENT_EXPENSE'
export const UPDATE_CLIENT_EXPENSE_FAILED = 'UDPATE_CLIENT_EXPENSE_FAILED'

export const DELETE_CLIENT_EXPENSE_BEGIN = 'DELETE_CLIENT_EXPENSE_BEGIN'
export const DELETE_CLIENT_EXPENSE = 'DELETE_CLIENT_EXPENSE'
export const DELETE_CLIENT_EXPENSE_FAILED = 'DELETE_CLIENT_EXPENSE_FAILED'