export const CREATE_BOOKING = "CREATE_BOOKING";
export const LIST_BOOKINGS = "LIST_BOOKINGS";
export const START_LIST_BOOKINGS = "START_LIST_BOOKINGS";
export const FINISH_LIST_BOOKINGS = "FINISH_LIST_BOOKINGS";
export const LIST_BOOKINGS_FAIL = "LIST_BOOKINGS_FAIL";
export const ADD_STAFF_MEMBER = "ADD_STAFF_MEMBER";

export const FETCH_ROOMS = "FETCH_ROOMS";
export const FINISH_FETCHING_ROOMS = "FINISH_FETCHING_ROOMS";
export const BEGIN_FETCHING_ROOMS = "BEGIN_FETCHING_ROOMS";

export const ADD_ROOM_START = "ADD_ROOM_START";
export const ADD_ROOM_DONE = "ADD_ROOM_DONE";
export const ADD_ROOM_FAILED = "ADD_ROOM_FAILED";

export const EDIT_ROOM_START = "EDIT_ROOM_START";
export const EDIT_ROOM_DONE = "EDIT_ROOM_DONE";
export const EDIT_ROOM_FAILED = "EDIT_ROOM_FAILED";

export const START_LOGIN = "START_LOGIN";
export const FINISH_LOGIN = "FINISH_LOGIN";
export const LOGIN_FAIL = "LOGIN_ERROR";

export const START_AUTO_LOGIN = "START_AUTO_LOGIN";
export const FINISH_AUTO_LOGIN = "FINISH_AUTO_LOGIN";
export const AUTO_LOGIN_FAILED = "AUTO_LOGIN_FAILED";
