# Generated by Django 2.2.12 on 2020-05-09 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClienExpenses',
            new_name='ClientExpenses',
        ),
    ]
