# Generated by Django 2.2.12 on 2020-04-04 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField(unique=True)),
                ('price', models.FloatField()),
                ('room_status', models.CharField(choices=[('IN_USE', 'In use'), ('AVAILABLE', 'Available'), ('OUT_OF_SERVICE', 'Out of service'), ('BOOKED', 'Booked')], default='AVAILABLE', max_length=50)),
                ('room_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='room.RoomCategory')),
            ],
        ),
    ]
