# Generated by Django 2.2.12 on 2020-04-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_auto_20200404_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomcategory',
            name='category_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
