# Generated by Django 2.2.12 on 2020-04-04 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_auto_20200404_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('IN_USE', 'In use'), ('OUT_OF_SERVICE', 'Out of service')], default='AVAILABLE', max_length=50),
        ),
    ]
