# Generated by Django 2.2.12 on 2020-05-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_auto_20200404_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_status',
            field=models.CharField(choices=[('AVAILABLE', 'available'), ('BOOKED', 'booked'), ('IN_USE', 'in use'), ('OUT_OF_SERVICE', 'Out of service')], default='AVAILABLE', max_length=50),
        ),
    ]
