# Generated by Django 2.2.12 on 2020-04-04 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('room', '0004_auto_20200404_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_name', models.CharField(max_length=255)),
                ('expected_check_in_date', models.DateTimeField()),
                ('expected_checkout_date', models.DateTimeField()),
                ('customer_booking_status', models.TextField(choices=[('Check-in', 'Check in'), ('Checkout', 'Checkout'), ('Booked', 'BOOKED')], default='Booked', max_length=50)),
                ('booking_status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed')], default='Pending', max_length=50)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('actual_check_in_date', models.DateTimeField(null=True)),
                ('actual_checkout_date', models.DateTimeField(null=True)),
                ('paid_advance', models.FloatField(null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bookings', to='room.Room')),
            ],
        ),
    ]
