# Generated by Django 2.2.12 on 2020-04-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20200405_0951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-expected_checkout_date']},
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer_booking_status',
            field=models.TextField(choices=[('Booked', 'Booked'), ('Check-in', 'Check in'), ('Checkout', 'Checkout')], default='Booked', max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='paid_advance',
            field=models.FloatField(default=0.0),
        ),
    ]
