# Generated by Django 2.2.12 on 2020-05-13 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20200513_0927'),
        ('booking', '0004_auto_20200513_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='client.HotelClient'),
            preserve_default=False,
        ),
    ]
